name: Tests

on: [push]

defaults:
  run:
    shell: sh

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: ./test_dir/project1
            terraform_version: 0.15.0
          - directory: ./test_dir/project2
            terraform_version: 1.3.3
          - directory: ./test_dir/project3/applications/backend-app
            terraform_version: 1.2.1
          - directory: ./test_dir/project3/applications/frontend-app
            terraform_version: 1.4.1
          - directory: ./test_dir/project4
            terraform_version: 1.6.1
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - run: ./install.sh
        working-directory: ${{ github.workspace }}
      - run: tfam fmt -recursive -check
  init:
    needs: [fmt]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - run: ./install.sh
        working-directory: ${{ github.workspace }}
      - run: tfam init -no-color
  validate:
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - run: ./install.sh
        working-directory: ${{ github.workspace }}
      - run: tfam init -no-color
      - run: tfam validate -no-color
  plan:
    needs: [validate]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
      - run: ./install.sh
        working-directory: ${{ github.workspace }}
      - run: tfam init -no-color
      - run: tfam plan -no-color

