name: Tests

on: [push]

defaults:
  run:
    shell: sh

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: ./install.sh
      - run: terraform fmt -recursive -check
  init:
    needs: [fmt]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
      - run: terraform init -no-color
  validate:
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
      - run: terraform init -no-color
      - run: terraform validate -no-color
  plan:
    needs: [validate]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - ./test_dir/project1
          - ./test_dir/project2
          - ./test_dir/project3
          - ./test_dir/project4
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
      - run: terraform init -no-color
      - run: terraform plan -no-color

